plugins {
    id("dev.nx.gradle.project-graph") version("0.1.10")
}
/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.2.1/samples
 */

allprojects {
    apply {
        plugin("dev.nx.gradle.project-graph")
    }
}